spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/serverdb
    username: root
  jpa:
    hibernate:
     ddl-auto: create
    properties:
        hibernate:
        spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true